
    create table leave_requests (
        end_date date,
        start_date date,
        leave_id bigint generated by default as identity,
        leave_type_id bigint not null,
        user_id bigint not null,
        reason varchar(255),
        status varchar(255) check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (leave_id)
    );

    create table leave_types (
        is_paid boolean not null,
        max_days_per_year integer not null,
        id bigint generated by default as identity,
        leave_name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        department varchar(255),
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        primary key (id)
    );

    alter table if exists leave_requests 
       add constraint FK26il0qrl79p6etqwn0ae6l43b 
       foreign key (leave_type_id) 
       references leave_types;

    alter table if exists leave_requests 
       add constraint FKh6s8bo5d59oy52b6nxfguf4yx 
       foreign key (user_id) 
       references users;

    create table leave_requests (
        end_date date,
        start_date date,
        leave_id bigint generated by default as identity,
        leave_type_id bigint not null,
        user_id bigint not null,
        reason varchar(255),
        status varchar(255) check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (leave_id)
    );

    create table leave_types (
        is_paid boolean not null,
        max_days_per_year integer not null,
        id bigint generated by default as identity,
        leave_name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        department varchar(255),
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        primary key (id)
    );

    alter table if exists leave_requests 
       add constraint FK26il0qrl79p6etqwn0ae6l43b 
       foreign key (leave_type_id) 
       references leave_types;

    alter table if exists leave_requests 
       add constraint FKh6s8bo5d59oy52b6nxfguf4yx 
       foreign key (user_id) 
       references users;

    create table leave_requests (
        end_date date,
        start_date date,
        leave_id bigint generated by default as identity,
        leave_type_id bigint not null,
        user_id bigint not null,
        reason varchar(255),
        status varchar(255) check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (leave_id)
    );

    create table leave_types (
        is_paid boolean not null,
        max_days_per_year integer not null,
        id bigint generated by default as identity,
        leave_name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        department varchar(255),
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        primary key (id)
    );

    alter table if exists leave_requests 
       add constraint FK26il0qrl79p6etqwn0ae6l43b 
       foreign key (leave_type_id) 
       references leave_types;

    alter table if exists leave_requests 
       add constraint FKh6s8bo5d59oy52b6nxfguf4yx 
       foreign key (user_id) 
       references users;

    create table leave_requests (
        end_date date,
        start_date date,
        leave_id bigint generated by default as identity,
        leave_type_id bigint not null,
        user_id bigint not null,
        reason varchar(255),
        status varchar(255) check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (leave_id)
    );

    create table leave_types (
        is_paid boolean not null,
        max_days_per_year integer not null,
        id bigint generated by default as identity,
        leave_name varchar(255),
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        department varchar(255),
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        primary key (id)
    );

    alter table if exists leave_requests 
       add constraint FK26il0qrl79p6etqwn0ae6l43b 
       foreign key (leave_type_id) 
       references leave_types;

    alter table if exists leave_requests 
       add constraint FKh6s8bo5d59oy52b6nxfguf4yx 
       foreign key (user_id) 
       references users;
